// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class TIOW_ACE_Mod {
		author = "Onkel Dolf";
		name = "EU Vanguard TIOW Addon";
		requiredAddons[] = {"A3_Characters_F", "A3_Weapons_F", /*"TIOWSpaceMarines",*/ "CadFoot", "TIOW_AutoWeapons", "Cadian_Weapons", "DKoK_Weapons", "ML700_M36"};
		requiredVersion = 0.1;
		units[] = {"TIOW_CadATBackpack"};
		weapons[] = {"Van_Gear", "Van_MedGear", "Van_Inf_Helm", "Van_InfBreather_Helm", "LasLMGBase", "VanguardLasLMG"};
		magazines[]= {"HighDensityM36KantRifle_mag", "150RndLasLmg_mag", "200RndLasLmg_mag", "TIOW_100Rnd_Stubber_mag", "TIOW_100Rnd_Stubber_mag_Tracer", "TIOW_100Rnd_Stubber_amput", "TIOW_100Rnd_Stubber_manstop", "TIOW_100Rnd_Stubber_expander", "TIOW_150Rnd_Stubber_mag", "TIOW_150Rnd_Stubber_mag_Tracer", "TIOW_150Rnd_Stubber_amput", "TIOW_150Rnd_Stubber_manstop", "TIOW_150Rnd_Stubber_expander"};
		worlds[] = {};
	};
};
