// Generated by unRap v1.06 by Kegetys

class Cfgweapons {
	class InventoryItem_Base_F;	// External class reference
	class ItemCore;	// External class reference
	class UniformItem;	// External class reference
	class HeadgearItem;	// External class reference
	class VestItem;	// External class reference
	class Rifle;	// External class reference
	
	class Rifle_Base_F : Rifle {
		class weaponSlotsInfo;	// External class reference
		class GunParticles;	// External class reference
	};
	class UGL_F;	// External class reference
	
	//////////////////////////////////////////////////////////////////////////////////////
	//TODO: Balance out the space marines so a Lucius pattern lasgun can't one shot them//
	//////////////////////////////////////////////////////////////////////////////////////
	
	/*
	class SM_Gear : ItemCore {
		scope = 0;
		allowedSlots[] = {BACKPACK_SLOT};
		hiddenSelections[] = {"camo"};
		
		class ItemInfo : VestItem {
			hiddenSelections[] = {"camo"};
			LOAD[] = {(0,0)};
		};
	};
	class TIOW_Mk7Vest : SM_Gear { // For more info go to https://community.bistudio.com/wiki/Arma_3_Soldier_Protection

		class ItemInfo : ItemInfo {

			
			class HitpointsProtectionInfo {
				class Neck {
					hitpointName = "HitNeck"; // reference to the hit point class defined in the man base class
					pen = 0.4; // Mod exclusive caculation
					armor = 250; // addition to armor of referenced hitpoint
					passThrough = 0.1; // multiplier of base passThrough defined in referenced hitpoint
				};
				
				class Arms {
					hitpointName = "HitArms";
					pen = 0.4; // Mod exclusive caculation
					armor = 100;
					passThrough = 0.1;
				};
				
				class Chest {
					hitpointName = "HitChest";
					pen = 0.4; // Mod exclusive caculation
					armor = 250;
					passThrough = 0.1;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					pen = 0.4; // Mod exclusive caculation
					armor = 250;
					passThrough = 0.1;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					pen = 0.4; // Mod exclusive caculation
					armor = 100;
					passThrough = 0.1;
				};
				
				class Pelvis {
					hitpointName = "HitPelvis";
					pen = 0.4; // Mod exclusive caculation
					armor = 100;
					passThrough = 0.1;
				};
				
				class Body {
					hitpointName = "HitBody";
					pen = 0.4; // Mod exclusive caculation
					armor = 100;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_Mk7Limbs_UM : TIOW_Mk7Vest {

		
		class ItemInfo : ItemInfo {

			
			class HitpointsProtectionInfo {
				class Neck {
					hitpointName = "HitNeck";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Arms {
					hitpointName = "HitArms";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Chest {
					hitpointName = "HitChest";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Pelvis {
					hitpointName = "HitPelvis";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 100;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_Mk7Limbs_IF : TIOW_Mk7Vest {
		
		class ItemInfo : ItemInfo {
			
			class HitpointsProtectionInfo {
				class Neck {
					hitpointName = "HitNeck";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Arms {
					hitpointName = "HitArms";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Chest {
					hitpointName = "HitChest";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Pelvis {
					hitpointName = "HitPelvis";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 100;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_Mk7Limbs_BA : TIOW_Mk7Vest {
		
		class ItemInfo : ItemInfo {
			
			class HitpointsProtectionInfo {
				class Neck {
					hitpointName = "HitNeck";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Arms {
					hitpointName = "HitArms";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Chest {
					hitpointName = "HitChest";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Pelvis {
					hitpointName = "HitPelvis";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 100;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_Mk7Limbs_BR : TIOW_Mk7Vest {
		
		class ItemInfo : ItemInfo {
			
			class HitpointsProtectionInfo {
				class Neck {
					hitpointName = "HitNeck";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Arms {
					hitpointName = "HitArms";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Chest {
					hitpointName = "HitChest";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Pelvis {
					hitpointName = "HitPelvis";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 100;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_Mk7Limbs_SL : TIOW_Mk7Vest {
		
		class ItemInfo : ItemInfo {
			
			class HitpointsProtectionInfo {
				class Neck {
					hitpointName = "HitNeck";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Arms {
					hitpointName = "HitArms";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Chest {
					hitpointName = "HitChest";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Pelvis {
					hitpointName = "HitPelvis";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 100;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_Mk7Limbs_RG : TIOW_Mk7Vest {
		
		class ItemInfo : ItemInfo {
			mass = 100;
			
			class HitpointsProtectionInfo {
				class Neck {
					hitpointName = "HitNeck";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Arms {
					hitpointName = "HitArms";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Chest {
					hitpointName = "HitChest";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Pelvis {
					hitpointName = "HitPelvis";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 100;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_Mk7Limbs_IH : TIOW_Mk7Vest {
		
		class ItemInfo : ItemInfo {
			
			class HitpointsProtectionInfo {
				class Neck {
					hitpointName = "HitNeck";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Arms {
					hitpointName = "HitArms";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Chest {
					hitpointName = "HitChest";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Pelvis {
					hitpointName = "HitPelvis";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 100;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_Mk7Limbs_WS : TIOW_Mk7Vest {
		
		class ItemInfo : ItemInfo {
			
			class HitpointsProtectionInfo {
				class Neck {
					hitpointName = "HitNeck";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Arms {
					hitpointName = "HitArms";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Chest {
					hitpointName = "HitChest";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Pelvis {
					hitpointName = "HitPelvis";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 100;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_Mk7Limbs_DA : TIOW_Mk7Vest {
		
		class ItemInfo : ItemInfo {
			
			class HitpointsProtectionInfo {
				class Neck {
					hitpointName = "HitNeck";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Arms {
					hitpointName = "HitArms";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Chest {
					hitpointName = "HitChest";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Pelvis {
					hitpointName = "HitPelvis";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 100;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_Mk7Limbs_SW : TIOW_Mk7Vest {
		
		class ItemInfo : ItemInfo {
			
			class HitpointsProtectionInfo {
				class Neck {
					hitpointName = "HitNeck";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Arms {
					hitpointName = "HitArms";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Chest {
					hitpointName = "HitChest";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Pelvis {
					hitpointName = "HitPelvis";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 100;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_Mk7Limbs_WB : TIOW_Mk7Vest {
		
		class ItemInfo : ItemInfo {
			class HitpointsProtectionInfo {
				class Neck {
					hitpointName = "HitNeck";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Arms {
					hitpointName = "HitArms";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Chest {
					hitpointName = "HitChest";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Pelvis {
					hitpointName = "HitPelvis";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 100;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_Mk7Limbs_IW : TIOW_Mk7Vest {
		
		class ItemInfo : ItemInfo {
			
			class HitpointsProtectionInfo {
				class Neck {
					hitpointName = "HitNeck";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Arms {
					hitpointName = "HitArms";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Chest {
					hitpointName = "HitChest";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Pelvis {
					hitpointName = "HitPelvis";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 100;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_Mk7Limbs_BL : TIOW_Mk7Vest {
		
		class ItemInfo : ItemInfo {
			
			class HitpointsProtectionInfo {
				class Neck {
					hitpointName = "HitNeck";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Arms {
					hitpointName = "HitArms";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Chest {
					hitpointName = "HitChest";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Pelvis {
					hitpointName = "HitPelvis";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 100;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_Mk7Limbs_WE : TIOW_Mk7Vest {
		
		class ItemInfo : ItemInfo {
			
			class HitpointsProtectionInfo {
				class Neck {
					hitpointName = "HitNeck";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Arms {
					hitpointName = "HitArms";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Chest {
					hitpointName = "HitChest";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Pelvis {
					hitpointName = "HitPelvis";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 100;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_Mk7Limbs_EC : TIOW_Mk7Vest {
		
		class ItemInfo : ItemInfo {
			
			class HitpointsProtectionInfo {
				class Neck {
					hitpointName = "HitNeck";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Arms {
					hitpointName = "HitArms";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Chest {
					hitpointName = "HitChest";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Pelvis {
					hitpointName = "HitPelvis";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 100;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_Mk7Limbs_AL : TIOW_Mk7Vest {
		
		class ItemInfo : ItemInfo {
			
			class HitpointsProtectionInfo {
				class Neck {
					hitpointName = "HitNeck";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Arms {
					hitpointName = "HitArms";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Chest {
					hitpointName = "HitChest";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Pelvis {
					hitpointName = "HitPelvis";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 100;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_Mk7Limbs_TS : TIOW_Mk7Vest {
		
		class ItemInfo : ItemInfo {
			
			class HitpointsProtectionInfo {
				class Neck {
					hitpointName = "HitNeck";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Arms {
					hitpointName = "HitArms";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Chest {
					hitpointName = "HitChest";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Pelvis {
					hitpointName = "HitPelvis";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 100;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_Mk7Limbs_NL : TIOW_Mk7Vest {
		
		class ItemInfo : ItemInfo {
			
			class HitpointsProtectionInfo {
				class Neck {
					hitpointName = "HitNeck";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Arms {
					hitpointName = "HitArms";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Chest {
					hitpointName = "HitChest";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Pelvis {
					hitpointName = "HitPelvis";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 100;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_Mk7Limbs_DG : TIOW_Mk7Vest {
		
		class ItemInfo : ItemInfo {
			
			class HitpointsProtectionInfo {
				class Neck {
					hitpointName = "HitNeck";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Arms {
					hitpointName = "HitArms";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Chest {
					hitpointName = "HitChest";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 250;
					passThrough = 0.1;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Pelvis {
					hitpointName = "HitPelvis";
					armor = 100;
					passThrough = 0.1;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 100;
					passThrough = 0.1;
				};
			};
		};
	};
	class SM_Helm_Base : ItemCore {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK7Helmet : SM_Helm_Base {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK7Helmet_UM : SM_Helm_Base {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK4Helmet_UM : TIOW_MK7Helmet_UM {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK7Helmet_IF : SM_Helm_Base {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK4Helmet_IF : TIOW_MK7Helmet_IF {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK7Helmet_BA : SM_Helm_Base {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK4Helmet_BA : TIOW_MK7Helmet_BA {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK7Helmet_BR : SM_Helm_Base {
		
		class ItemInfo : HeadgearItem {
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK4Helmet_BR : TIOW_MK7Helmet_BR {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK7Helmet_SL : SM_Helm_Base {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK4Helmet_SL : TIOW_MK7Helmet_SL {
		
		class ItemInfo : HeadgearItem {
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK7Helmet_RG : SM_Helm_Base {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK4Helmet_RG : TIOW_MK7Helmet_RG {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK7Helmet_IH : SM_Helm_Base {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK4Helmet_IH : TIOW_MK7Helmet_IH {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK7Helmet_WS : SM_Helm_Base {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK4Helmet_WS : TIOW_MK7Helmet_WS {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK7Helmet_DA : SM_Helm_Base {

		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK4Helmet_DA : TIOW_MK7Helmet_DA {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK7Helmet_SW : SM_Helm_Base {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK4Helmet_SW : TIOW_MK7Helmet_SW {

		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK7Helmet_WB : SM_Helm_Base {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK4Helmet_WB : TIOW_MK7Helmet_WB {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK7Helmet_IW : SM_Helm_Base {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK7Helmet2_IW : SM_Helm_Base {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK4Helmet_IW : TIOW_MK7Helmet_IW {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK7Helmet_BL : SM_Helm_Base {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK4Helmet_BL : TIOW_MK7Helmet_BL {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK7Helmet_WE : SM_Helm_Base {
		
		class ItemInfo : HeadgearItem {
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK4Helmet_WE : TIOW_MK7Helmet_WE {
		
		class ItemInfo : HeadgearItem {
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK7Helmet_EC : SM_Helm_Base {
		
		class ItemInfo : HeadgearItem {
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK4Helmet_EC : TIOW_MK7Helmet_EC {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK7Helmet_AL : SM_Helm_Base {
		
		class ItemInfo : HeadgearItem {
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK4Helmet_AL : TIOW_MK7Helmet_AL {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK7Helmet_TS : SM_Helm_Base {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK4Helmet_TS : TIOW_MK7Helmet_TS {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK7Helmet_NL : SM_Helm_Base {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK4Helmet_NL : TIOW_MK7Helmet_NL {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK7Helmet_DG : SM_Helm_Base {
		
		class ItemInfo : HeadgearItem {
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	class TIOW_MK4Helmet_DG : TIOW_MK7Helmet_DG {
		
		class ItemInfo : HeadgearItem {
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 45;
					passThrough = 0.1;
				};
			};
		};
	};
	*/
	
	class Rifle;
	class Rifle_Base_F: Rifle
	{
		class WeaponSlotsInfo;
		class GunParticles;
	};
	class UGL_F;
	class ItemCore;
	class InventoryItem_Base_F;
	class InventoryOpticsItem_Base_F;
	class InventoryMuzzleItem_Base_F;
	class InventoryUnderItem_Base_F;
	class MuzzleSlot;
	class CowsSlot;
	class PointerSlot;
	class UnderBarrelSlot;
	class hgun_ACPC2_F;

	class KriegHeavyStubber: Rifle_Base_F
	{
		scope=1;
		scopeArsenal=1;
		scopeCurator=1;
		magazineWells[]={};
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			class MuzzleSlot: MuzzleSlot
			{
				compatibleItems[]={};
				iconPosition[]={0,0.45};
				iconScale=0.2;
				iconPicture="\A3\Weapons_F\Data\UI\attachment_muzzle.paa";
				iconPinpoint="Center";
			};
			class CowsSlot: CowsSlot
			{
				iconPosition[]={0.5,0.35};
				compatibleItems[]={};
				iconScale=0.2;
			};
			class PointerSlot: PointerSlot
			{
				iconPosition[]={0.2,0.45};
				compatibleItems[]={};
				iconScale=0.25;
			};
			class UnderBarrelSlot: UnderBarrelSlot
			{
				linkProxy="\A3\Data_f_Mark\proxies\weapon_slots\UNDERBARREL";
				iconPosition[]={0.2,0.7};
				iconScale=0.2;
				compatibleItems[]=
				{
					"KriegHeavyStubberDK_Bipod"
				};
			};
			mass=175;
		};
		caseless[]=
		{
			"",
			1,
			1,
			1
		};
		model="\TIOW_AutoWeapons\Model\Krieg_Heavy_Stubber.p3d";
		soundBullet[]=
		{
			"caseless",
			1
		};
		drySound[]=
		{
			"A3\Sounds_F\arsenal\weapons\Rifles\MX\dry_Mx",
			0.56234097,
			1,
			10
		};
		reloadMagazineSound[]=
		{
			"A3\Sounds_F\arsenal\weapons\Rifles\MX\Reload_MX",
			1,
			1,
			10
		};
		changeFiremodeSound[]=
		{
			"A3\Sounds_F\arsenal\weapons\Rifles\MX\firemode_Mx",
			0.177828,
			1,
			5
		};
		modes[]=
		{
			"Single",
			"FullAuto",
			"fullauto_medium",
			"single_medium_optics1",
			"single_far_optics2"
		};
		class Single: Mode_SemiAuto
		{
			dispersion=0.00035;
			soundContinuous=0;
			reloadTime=0.4;
			recoil="recoil_single_gm6";
			recoilProne="recoil_single_prone_gm6";
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				closure1[]=
				{
					"A3\Sounds_F\arsenal\weapons\LongRangeRifles\GM6_Lynx\GM6_closure_01",
					0.39810699,
					1,
					40
				};
				closure2[]=
				{
					"A3\Sounds_F\arsenal\weapons\LongRangeRifles\GM6_Lynx\GM6_closure_02",
					0.39810699,
					1,
					40
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\Sounds_F\arsenal\weapons\LongRangeRifles\GM6_Lynx\GM6_short_01",
					7.9432802,
					1,
					2200
				};
				begin2[]=
				{
					"A3\Sounds_F\arsenal\weapons\LongRangeRifles\GM6_Lynx\GM6_short_02",
					7.9432802,
					1,
					2200
				};
				soundBegin[]=
				{
					"begin1",
					0.5,
					"begin2",
					0.5
				};
				class SoundTails
				{
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\GM6_Lynx\GM6_tail_forest",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\GM6_Lynx\GM6_tail_houses",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\GM6_Lynx\GM6_tail_interior",
							1.99526,
							1,
							2200
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\GM6_Lynx\GM6_tail_meadows",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\GM6_Lynx\GM6_tail_trees",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
				};
				soundSetShot[]=
				{
					"GM6Lynx_Shot_SoundSet",
					"GM6Lynx_Tail_SoundSet",
					"GM6Lynx_InteriorTail_SoundSet"
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				soundSetShot[]=
				{
					"MX_silencerShot_SoundSet",
					"MX_silencerTail_SoundSet"
				};
				begin1[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\MX\Silencer_Mx_short_01",
					0.79432797,
					1,
					400
				};
				begin2[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\MX\Silencer_Mx_short_02",
					0.79432797,
					1,
					400
				};
				begin3[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\MX\Silencer_Mx_short_03",
					0.79432797,
					1,
					400
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin1",
					0.34
				};
				class SoundTails
				{
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\MX\Silencer_Mx_tail_interior",
							1,
							1,
							400
						};
						frequency=1;
						volume="interior";
					};
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\MX\Silencer_mx_tail_trees",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\MX\Silencer_mx_tail_forest",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\MX\Silencer_mx_tail_meadows",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\MX\Silencer_mx_tail_houses",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
		};
		class FullAuto: Mode_FullAuto
		{
			soundContinuous=0;
			soundBurst=0;
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				closure1[]=
				{
					"A3\Sounds_F\arsenal\weapons\LongRangeRifles\GM6_Lynx\GM6_closure_01",
					0.316228,
					1,
					10
				};
				closure2[]=
				{
					"A3\Sounds_F\arsenal\weapons\LongRangeRifles\GM6_Lynx\GM6_closure_02",
					0.316228,
					1.1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
				soundSet="";
			};
			class StandardSound: BaseSoundModeType
			{
				soundSetShot[]=
				{
					"GM6Lynx_Shot_SoundSet",
					"GM6Lynx_Tail_SoundSet",
					"GM6Lynx_InteriorTail_SoundSet"
				};
				begin1[]=
				{
					"A3\Sounds_F\arsenal\weapons\LongRangeRifles\GM6_Lynx\GM6_closure_01",
					3.1622801,
					1,
					1800
				};
				begin2[]=
				{
					"A3\Sounds_F\arsenal\weapons\LongRangeRifles\GM6_Lynx\GM6_closure_02",
					3.1622801,
					1,
					1800
				};
				begin3[]=
				{
					"A3\Sounds_F\arsenal\weapons\LongRangeRifles\GM6_Lynx\GM6_closure_01",
					3.1622801,
					1,
					1800
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin1",
					0.34
				};
				class SoundTails
				{
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\GM6_Lynx\GM6_closure_01",
							1.58489,
							1,
							1800
						};
						frequency=1;
						volume="interior";
					};
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\GM6_Lynx\GM6_closure_01",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\GM6_Lynx\GM6_closure_01",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\GM6_Lynx\GM6_closure_01",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\GM6_Lynx\GM6_closure_01",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				soundSetShot[]=
				{
					"MX_silencerShot_SoundSet",
					"MX_silencerTail_SoundSet"
				};
				begin1[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\MX\Silencer_Mx_short_01",
					0.79432797,
					1,
					400
				};
				begin2[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\MX\Silencer_Mx_short_02",
					0.79432797,
					1,
					400
				};
				begin3[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\MX\Silencer_Mx_short_03",
					0.79432797,
					1,
					400
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin1",
					0.34
				};
				class SoundTails
				{
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\MX\Silencer_Mx_tail_interior",
							1,
							1,
							400
						};
						frequency=1;
						volume="interior";
					};
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\MX\Silencer_mx_tail_trees",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\MX\Silencer_mx_tail_forest",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\MX\Silencer_mx_tail_meadows",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\MX\Silencer_mx_tail_houses",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
			reloadTime=0.096;
			dispersion=0.00087;
			recoil="recoil_auto_mx";
			recoilProne="recoil_auto_prone_mx";
			minRange=0;
			minRangeProbab=0.89999998;
			midRange=15;
			midRangeProbab=0.69999999;
			maxRange=1250;
			maxRangeProbab=0.1;
			aiRateOfFire=3;
		};
		magazines[]=
		{
			"TIOW_50Rnd_Stubber_mag",
			"TIOW_50Rnd_Stubber_mag_Tracer",
			"TIOW_50Rnd_Stubber_amput",
			"TIOW_50Rnd_Stubber_manstop",
			"TIOW_50Rnd_Stubber_expander",
			"TIOW_100Rnd_Stubber_mag",
			"TIOW_100Rnd_Stubber_mag_Tracer",
			"TIOW_100Rnd_Stubber_amput",
			"TIOW_100Rnd_Stubber_manstop",
			"TIOW_100Rnd_Stubber_expander",
			"TIOW_150Rnd_Stubber_mag",
			"TIOW_150Rnd_Stubber_mag_Tracer",
			"TIOW_150Rnd_Stubber_amput",
			"TIOW_150Rnd_Stubber_manstop",
			"TIOW_150Rnd_Stubber_expander"
		};
		class Library
		{
			libTextDesc="";
		};
		reloadAction="GestureReloadMX";
		picture="\A3\weapons_F\Rifles\MX\data\UI\gear_mx_lmg_X_CA.paa";
		UiPicture="\A3\weapons_f\data\UI\icon_MG_CA.paa";
		recoil="recoil_mx";
		maxZeroing=1000;
		discreteDistanceInitIndex=0;
		maxRecoilSway=0.0125;
		swayDecaySpeed=1.25;
		class GunParticles: GunParticles
		{
			class SecondEffect
			{
				positionName="Nabojnicestart";
				directionName="Nabojniceend";
				effectName="CaselessAmmoCloud";
			};
		};
		distanceZoomMin=300;
		distanceZoomMax=300;
		descriptionShort="";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\A3\Weapons_F\Rifles\Khaybar\data\anim\katiba_gl.rtm"
		};
		class fullauto_medium: FullAuto
		{
			showToPlayer=0;
			burst=5;
			minRange=2;
			minRangeProbab=0.5;
			midRange=75;
			midRangeProbab=0.7;
			maxRange=1500;
			maxRangeProbab=0.05;
			aiRateOfFire=2;
			aiRateOfFireDistance=500;
		};
		class single_medium_optics1: Single
		{
			requiredOpticType=1;
			showToPlayer=0;
			minRange=1;
			minRangeProbab=0.2;
			midRange=2;
			midRangeProbab=0.7;
			maxRange=3;
			maxRangeProbab=0.2;
			aiRateOfFire=3;
			aiRateOfFireDistance=600;
		};
		class single_far_optics2: single_medium_optics1
		{
			requiredOpticType=2;
			showToPlayer=0;
			minRange=1;
			minRangeProbab=0.1;
			midRange=2;
			midRangeProbab=0.6;
			maxRange=3;
			maxRangeProbab=0.05;
			aiRateOfFire=4;
			aiRateOfFireDistance=700;
		};
		aiDispersionCoefY=6;
		aiDispersionCoefX=4;
	};
	
	class Pistol;
	class Pistol_Base_F: Pistol
	{
		class WeaponSlotsInfo;
	};
	class Rifle;
	class Rifle_Base_F: Rifle
	{
		class WeaponSlotsInfo;
		class GunParticles;
	};
	class UGL_F;
	class Launcher;
	class Launcher_Base_F: Launcher
	{
		class WeaponSlotsInfo;
	};
	class ItemCore;
	class InventoryItem_Base_F;
	class InventoryOpticsItem_Base_F;
	class Type14Heavy;
	class TIOW_SM_Ragefire_PlasmaGun;
	class DK_PlasmaGun;
	class arifle_MX_Base_F: Rifle_Base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="lasgunbase";
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag_Tracer"
		};
		class Library
		{
			libTextDesc="$STR_A3_CfgWeapons_arifle_XMX_Library0";
		};
		reloadAction="GestureReloadMX";
		recoil="recoil_mx";
		maxZeroing=1000;
		discreteDistanceInitIndex=0;
		maxRecoilSway=0.0125;
		swayDecaySpeed=1.25;
		class GunParticles: GunParticles
		{
			class SecondEffect
			{
				positionName="Nabojnicestart";
				directionName="Nabojniceend";
				effectName="CaselessAmmoCloud";
			};
		};
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			class MuzzleSlot: MuzzleSlot
			{
				linkProxy="\A3\data_f\proxies\weapon_slots\MUZZLE";
				compatibleItems[]=
				{
					"muzzle_snds_h"
				};
				iconPosition[]={0,0.45};
				iconScale=0.2;
			};
			class CowsSlot: CowsSlot
			{
				iconPosition[]={0.5,0.35};
				iconScale=0.2;
			};
			class PointerSlot: PointerSlot
			{
				iconPosition[]={0.2,0.45};
				iconScale=0.25;
			};
		};
		distanceZoomMin=300;
		distanceZoomMax=300;
		descriptionShort="$STR_A3_CfgWeapons_XM_base_F0";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\A3\Weapons_F\Rifles\MX\data\Anim\mx.rtm"
		};
		modes[]=
		{
			"Single",
			"FullAuto",
			"fullauto_medium",
			"single_medium_optics1",
			"single_far_optics2"
		};
		class Single: Mode_SemiAuto
		{
			reloadTime=0.096;
			recoil="recoil_single_mx";
			recoilProne="recoil_single_prone_mx";
			dispersion=0.00087;
			minRange=2;
			minRangeProbab=0.5;
			midRange=200;
			midRangeProbab=0.7;
			maxRange=400;
			maxRangeProbab=0.3;
		};
		class FullAuto: Mode_FullAuto
		{
			reloadTime=0.096;
			dispersion=0.00087;
			recoil="recoil_auto_mx";
			recoilProne="recoil_auto_prone_mx";
			minRange=0;
			minRangeProbab=0.8;
			midRange=15;
			midRangeProbab=0.7;
			maxRange=30;
			maxRangeProbab=0.1;
			aiRateOfFire=1e-006;
		};
		class fullauto_medium: FullAuto
		{
			showToPlayer=0;
			burst=3;
			aiBurstTerminable=1;
			minRange=2;
			minRangeProbab=0.5;
			midRange=75;
			midRangeProbab=0.7;
			maxRange=150;
			maxRangeProbab=0.05;
			aiRateOfFire=2;
			aiRateOfFireDistance=200;
		};
		class single_medium_optics1: Single
		{
			requiredOpticType=1;
			showToPlayer=0;
			minRange=2;
			minRangeProbab=0.2;
			midRange=450;
			midRangeProbab=0.7;
			maxRange=600;
			maxRangeProbab=0.2;
			aiRateOfFire=6;
			aiRateOfFireDistance=600;
		};
		class single_far_optics2: single_medium_optics1
		{
			requiredOpticType=2;
			showToPlayer=0;
			minRange=100;
			minRangeProbab=0.1;
			midRange=500;
			midRangeProbab=0.6;
			maxRange=700;
			maxRangeProbab=0.05;
			aiRateOfFire=8;
			aiRateOfFireDistance=700;
		};
		class GL_3GL_F: UGL_F
		{
			displayName="$STR_A3_cfgweapons_3gl0";
			descriptionShort="$STR_A3_cfgweapons_3gl1";
			useModelOptics=0;
			useExternalOptic=0;
			magazines[]=
			{
				"1Rnd_HE_Grenade_shell",
				"UGL_FlareWhite_F",
				"UGL_FlareGreen_F",
				"UGL_FlareRed_F",
				"UGL_FlareYellow_F",
				"UGL_FlareCIR_F",
				"1Rnd_Smoke_Grenade_shell",
				"1Rnd_SmokeRed_Grenade_shell",
				"1Rnd_SmokeGreen_Grenade_shell",
				"1Rnd_SmokeYellow_Grenade_shell",
				"1Rnd_SmokePurple_Grenade_shell",
				"1Rnd_SmokeBlue_Grenade_shell",
				"1Rnd_SmokeOrange_Grenade_shell",
				"3Rnd_HE_Grenade_shell",
				"3Rnd_UGL_FlareWhite_F",
				"3Rnd_UGL_FlareGreen_F",
				"3Rnd_UGL_FlareRed_F",
				"3Rnd_UGL_FlareYellow_F",
				"3Rnd_UGL_FlareCIR_F",
				"3Rnd_Smoke_Grenade_shell",
				"3Rnd_SmokeRed_Grenade_shell",
				"3Rnd_SmokeGreen_Grenade_shell",
				"3Rnd_SmokeYellow_Grenade_shell",
				"3Rnd_SmokePurple_Grenade_shell",
				"3Rnd_SmokeBlue_Grenade_shell",
				"3Rnd_SmokeOrange_Grenade_shell"
			};
			cameraDir="OP_look";
			discreteDistance[]={50,75,100,150,200,250,300,350,400};
			discreteDistanceCameraPoint[]=
			{
				"OP_eye_50",
				"OP_eye_75",
				"OP_eye_100",
				"OP_eye_150",
				"OP_eye_200",
				"OP_eye_250",
				"OP_eye_300",
				"OP_eye_350",
				"OP_eye_400"
			};
			discreteDistanceInitIndex=1;
			reloadAction="GestureReloadMXUGL";
			reloadMagazineSound[]=
			{
				"A3\Sounds_F\arsenal\weapons\Rifles\MX\Mx_UGL_reload",
				1,
				1,
				10
			};
		};
		aiDispersionCoefY=6;
		aiDispersionCoefX=4;
	};

	class M36KantRifleBase: arifle_MX_Base_F
	{
		author="1st Legion";
		scope=0;
		scopeCurator=0;
		scopeArsenal=0;
		displayName="M36 Kantrael Pattern Lasrifle";
		model="\Cadian_Weapons\Model\M36KantRifle.p3d";
		reloadAction="GestureReloadMXCompact";
		picture="\Cadian_Weapons\Icon\KantraelLasrifle_ca.paa";
		muzzles[]=
		{
			"this"
		};
		magazineWell[]={};
		magazines[]=
		{
			"M36KantRifle_mag",
			"HighDensityM36KantRifle_mag"
		};
		rightHandIKCurve[]={1};
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\Cadian_Weapons\Anim\M36KantRifle.rtm"
		};
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=80;
			class MuzzleSlot: MuzzleSlot
			{
				linkProxy="\A3\data_f\proxies\weapon_slots\MUZZLE";
				compatibleItems[]={};
				iconPosition[]={0,0.44999999};
				iconScale=0.2;
			};
			class CowsSlot: CowsSlot
			{
				iconPosition[]={0.5,0.34999999};
				iconScale=0.2;
				compatibleItems[]=
				{
					"TIOW_2x4xScope_1",
					"TIOW_6xScope_1",
					"TIOW_10xScope_1"
				};
			};
			class PointerSlot: PointerSlot
			{
				iconPosition[]={0.2,0.44999999};
				iconScale=0.25;
				compatibleItems[]={};
			};
		};
		inertia=0.40000001;
		aimTransitionSpeed=1.2;
		dexterity=1.6;
		initSpeed=720;
		recoil="recoil_lasgun";
		modelOptics="\DKoK_Weapons\Type14_Optic.p3d";
		class OpticsModes
		{
			class TWS
			{
				opticsID=1;
				useModelOptics=1;
				opticsPPEffects[]=
				{
					"OpticsCHAbera1",
					"OpticsBlur1"
				};
				opticsZoomMin=0.039999999;
				opticsZoomMax=0.0625;
				opticsZoomInit=0.0625;
				discreteDistance[]={100,200,300,400,500,600,700,800,900,1000,1100,1200,1300,1400,1500,1600};
				discreteDistanceInitIndex=2;
				distanceZoomMin=100;
				distanceZoomMax=1600;
				discretefov[]={0.0625,0.025};
				discreteInitIndex=0;
				modelOptics[]=
				{
					"\A3\Weapons_f\acc\reticle_tws_mg",
					"\A3\Weapons_f\acc\reticle_tws_mg_NFOW"
				};
				memoryPointCamera="opticView";
				visionMode[]=
				{
					"Normal"
				};
				opticsFlare=1;
				opticsDisablePeripherialVision=1;
				cameraDir="";
			};
			class Iron: TWS
			{
				opticsID=2;
				useModelOptics=0;
				opticsPPEffects[]=
				{
					"",
					""
				};
				opticsFlare=0;
				opticsDisablePeripherialVision=0;
				opticsZoomMin=0.15000001;
				opticsZoomMax=0.40000001;
				opticsZoomInit=0.5;
				memoryPointCamera="eye";
				visionMode[]={};
				discretefov[]={};
				distanceZoomMin=200;
				distanceZoomMax=200;
				discreteDistance[]={200};
				discreteDistanceInitIndex=0;
			};
		};
		maxZeroing=1000;
		class ItemInfo
		{
			priority=1;
		};
		descriptionShort="Lucius Pattern No.98 Lasgun - Fires at a higher charge range than most lasguns, giving significantly more punch, at the cost of recharge rate and quicker power pack depletion - Power pack only good for 25 shots. Standard issue Death Korps weapon.";
		selectionFireAnim="muzzleFlash";
		modes[]=
		{
			"Single",
			"Burst",
			"single_medium_optics1",
			"single_far_optics2"
		};
		class Single: Mode_SemiAuto
		{
			reloadTime=0.096000001;
			recoil="recoil_pistol_light";
			recoilProne="recoil_prone_pistol_light";
			dispersion=0.00034999999;
			minRange=200;
			minRangeProbab=0.5;
			midRange=400;
			midRangeProbab=0.69999999;
			maxRange=750;
			maxRangeProbab=0.30000001;
			soundContinuous=0;
			soundBurst=0;
			sounds[]=
			{
				"StandardSound"
			};
			class BaseSoundModeType
			{
				closure1[]=
				{
					"\DKoK_Weapons\Sound\close_1.ogg",
					0.316228,
					1,
					10
				};
				closure2[]=
				{
					"\DKoK_Weapons\Sound\close_2.ogg",
					0.316228,
					1.1,
					10
				};
				soundClosure[]={};
			};
			class StandardSound: BaseSoundModeType
			{
				soundSetShot[]=
				{
					"Lasgun_Shot_SoundSet",
					"Lasgun_Tail_SoundSet",
					"Lasgun_InteriorTail_SoundSet"
				};
				begin1[]=
				{
					"\DKoK_Weapons\Sound\close_1.ogg",
					3.1622801,
					1,
					1800
				};
				begin2[]=
				{
					"\DKoK_Weapons\Sound\close_2.ogg",
					3.1622801,
					1,
					1800
				};
				begin3[]=
				{
					"\DKoK_Weapons\Sound\close_3.ogg",
					3.1622801,
					1,
					1800
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin1",
					0.34
				};
				class SoundTails
				{
					class TailInterior
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							2.2387199,
							1,
							1800
						};
						frequency=1;
						volume="interior";
					};
					class TailTrees
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailMeadows
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
		};
		class Burst: Mode_Burst
		{
			sounds[]=
			{
				"StandardSound"
			};
			class BaseSoundModeType
			{
				closure1[]=
				{
					"\DKoK_Weapons\Sound\close_1.ogg",
					1,
					1,
					10
				};
				closure2[]=
				{
					"\DKoK_Weapons\Sound\close_1.ogg",
					1,
					1.1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\DKoK_Weapons\Sound\close_1.ogg",
					2.8183801,
					1,
					1200
				};
				begin2[]=
				{
					"\DKoK_Weapons\Sound\close_1.ogg",
					2.8183801,
					1,
					1200
				};
				begin3[]=
				{
					"\DKoK_Weapons\Sound\close_1.ogg",
					2.8183801,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
				class SoundTails
				{
					class TailInterior
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							1.58489,
							1,
							1200
						};
						frequency=1;
						volume="interior";
					};
					class TailTrees
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							1,
							1,
							1200
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							1,
							1,
							1200
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailMeadows
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							1,
							1,
							1200
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							1,
							1,
							1200
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
				SoundSetShot[]=
				{
					"Lasgun_Shot_SoundSet",
					"Lasgun_Tail_SoundSet",
					"Lasgun_InteriorTail_SoundSet"
				};
			};
			soundBurst=0;
			burst=3;
			reloadTime=0.096;
			dispersion=0.00035;
			recoil="recoil_pistol_light";
			recoilProne="recoil_prone_pistol_light";
			minRange=2;
			minRangeProbab=0.3;
			midRange=50;
			midRangeProbab=0.7;
			maxRange=200;
			maxRangeProbab=0.05;
			aiRateOfFire=1;
			aiRateOfFireDistance=250;
		};
		class single_medium_optics1: Single
		{
			requiredOpticType=1;
			showToPlayer=0;
			minRange=2;
			minRangeProbab=0.2;
			midRange=450;
			midRangeProbab=0.7;
			maxRange=600;
			maxRangeProbab=0.2;
			aiRateOfFire=2;
			aiRateOfFireDistance=600;
		};
		class single_far_optics2: single_medium_optics1
		{
			requiredOpticType=2;
			showToPlayer=0;
			minRange=100;
			minRangeProbab=0.1;
			midRange=500;
			midRangeProbab=0.6;
			maxRange=1200;
			maxRangeProbab=0.05;
			aiRateOfFire=4;
			aiRateOfFireDistance=1200;
		};
		aiDispersionCoefY=6;
		aiDispersionCoefX=4;
	};

	class Uniform_Base;
	class UniformItem;
	class InventoryItem_Base_F;
	class ItemCore;
	class Binocular;
	class VestItem: InventoryItem_Base_F
	{
		type=701;
		hiddenSelections[]={};
		armor="5*0";
		passThrough=1;
		hitpointName="HitBody";
	};

	class Cad_Gear_Vest2: ItemCore
	{
		scope=1;
		allowedSlots[]={901};
		hiddenSelections[]=
		{
			"camo",
			"camoB",
			"RegimentCamo"
		};
		class ItemInfo: VestItem
		{
			hiddenSelections[]=
			{
				"camo",
				"camoB",
				"RegimentCamo"
			};
		};
	};

    class Cad_Gear2: Cad_Gear_Vest2
	{
		scope=1;
		displayName="[Cadian] Flak Armor 2";
		picture="\A3\characters_f\Data\UI\icon_V_TacVest_blk_CA.paa";
		model="\CadFoot\Model\CadianArmor.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camoB",
			"RegimentCamo"
		};
		hiddenSelectionsTextures[]={};
		class ItemInfo: ItemInfo
		{
			uniformModel="\CadFoot\Model\CadianArmor.p3d";
			containerClass="Supply80";
			overlaySelectionsInfo[]=
			{
				"ghillie_hide"
			};
			class HitpointsProtectionInfo
			{
				class Neck
				{
					hitpointName="HitNeck";
					armor=78;
					passThrough=0.5;
				};
				class Arms
				{
					hitpointName="HitArms";
					armor=78;
					passThrough=0.5;
				};
				class Chest
				{
					hitpointName="HitChest";
					armor=78;
					passThrough=0.6;
				};
				class Diaphragm
				{
					hitpointName="HitDiaphragm";
					armor=78;
					passThrough=0.6;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=16;
					passThrough=0.3;
				};
				class Pelvis
				{
					hitpointName="HitPelvis";
					armor=16;
					passThrough=0.3;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.6;
				};
			};
		};
	};

    class Van_Gear: Cad_Gear2
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="[Vanguard] Flak Armor";
		picture="\CadFoot\Icon\CadianArmor_ca.paa";
		model="\CadFoot\Model\CadianArmor.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camoB",
			"RegimentCamo"
		};
		hiddenSelectionsTextures[]=
		{
			"CadFoot\Data\Textures\GM_FlakArmor_776_co.paa",
			"",
			"CadFoot\Data\Textures\GM_FlakArmorReg_776_ca.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\CadFoot\Model\CadianArmor.p3d";
			containerClass="Supply80";
			overlaySelectionsInfo[]=
			{
				"ghillie_hide"
			};
			class HitpointsProtectionInfo
			{
				class Neck
				{
					hitpointName="HitNeck";
					armor=80;
					passThrough=0.3;
				};
				class Arms
				{
					hitpointName="HitArms";
					armor=80;
					passThrough=0.3;
				};
				class Chest
				{
					hitpointName="HitChest";
					armor=80;
					passThrough=0.3;
				};
				class Diaphragm
				{
					hitpointName="HitDiaphragm";
					armor=80;
					passThrough=0.3;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=35;
					passThrough=0.1;
				};
				class Pelvis
				{
					hitpointName="HitPelvis";
					armor=35;
					passThrough=0.1;
				};
				class Body
				{
					hitpointName="HitBody";
					armor=80;
					passThrough=0.3;
				};
				/*
				class Neck
				{
					hitpointName="HitNeck";
					armor=175.5; //125% increase of the normal Cadian flak armour 175.5
					passThrough=0.5;
				};
				class Arms
				{
					hitpointName="HitArms";
					armor=175.5;
					passThrough=0.5;
				};
				class Chest
				{
					hitpointName="HitChest";
					armor=175.5;
					passThrough=0.6;
				};
				class Diaphragm
				{
					hitpointName="HitDiaphragm";
					armor=175.5;
					passThrough=0.6;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=36;
					passThrough=0.3;
				};
				class Pelvis
				{
					hitpointName="HitPelvis";
					armor=36;
					passThrough=0.3;
				};
				class Body
				{
					hitpointName="HitBody";
					armor=175.5;
					passThrough=0.6;
				};
				*/
			};
		};
	};

	class Van_MedGear: Cad_Gear2
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="[Vanguard] Medicae Flak Armor";
		picture="\CadFoot\Icon\CadianArmor_ca.paa";
		model="\CadFoot\Model\CadianArmor.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camoB",
			"RegimentCamo"
		};
		hiddenSelectionsTextures[]=
		{
			"CadFoot\Data\Textures\GM_FlakArmor_776_co.paa",
			"",
			"CadFoot\Data\Textures\MED_FlakArmorReg_776_ca.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\CadFoot\Model\CadianArmor.p3d";
			containerClass="Supply80";
			overlaySelectionsInfo[]=
			{
				"ghillie_hide"
			};
			class HitpointsProtectionInfo
			{
				class Neck
				{
					hitpointName="HitNeck";
					armor=100; //~54% increase of the normal Cadian flak armour
					passThrough=0.9;
				};
				class Arms
				{
					hitpointName="HitArms";
					armor=100;
					passThrough=0.9;
				};
				class Chest
				{
					hitpointName="HitChest";
					armor=100;
					passThrough=0.9;
				};
				class Diaphragm
				{
					hitpointName="HitDiaphragm";
					armor=100;
					passThrough=0.9;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=24;
					passThrough=0.6;
				};
				class Pelvis
				{
					hitpointName="HitPelvis";
					armor=24;
					passThrough=0.6;
				};
				class Body
				{
					hitpointName="HitBody";
					armor=100;
					passThrough=0.9;
				};
			};
		};
	};

	class Cad_Inf_Helm2: ItemCore
	{
		scope=1;
		displayName="[Cadian] Shocktrooper Helmet 2";
		picture="\A3\characters_f\Data\UI\icon_H_Cap_blk_CA.paa";
		model="\CadFoot\Model\CadianHelmet.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camoB",
			"Camo1"
		};
		hiddenSelectionsTextures[]={};
		class ItemInfo: HeadgearItem
		{
			mass=45;
			uniformModel="\CadFoot\Model\CadianHelmet.p3d";
			allowedSlots[]={801,901,701,605};
			modelSides[]={6};
			hiddenSelections[]=
			{
				"camo",
				"camoB",
				"Camo1"
			};
			hiddenSelectionsTextures[]={};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=35;
					passThrough=0.1;
				};
			};
		};
	};

	class Van_Inf_Helm: Cad_Inf_Helm2
	{
		scope=2;
		scopeArsenal=2;
		scopeCurator=2;
		displayName="[Vanguard] Helmet";
		picture="\CadFoot\Icon\CadianHelmet_ca.paa";
		model="\CadFoot\Model\CadianHelmet.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"CadFoot\Data\Textures\GM_Helmet_776_co.paa"
		};
		class ItemInfo: HeadgearItem
		{
			mass=45;
			uniformModel="\CadFoot\Model\CadianHelmet.p3d";
			allowedSlots[]={801,901,701,605};
			modelSides[]={6};
			hiddenSelections[]=
			{
				"camo"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=78.75; //125% buff
					passThrough=0.1;
				};
			};
		};
	};

	class Van_InfBreather_Helm: Cad_Inf_Helm2
	{
		scope=2;
		scopeArsenal=2;
		scopeCurator=2;
		displayName="[Vanguard] Helmet, Hostile Environment";
		picture="\CadFoot\Icon\CadianHelmetRebreather_ca.paa";
		model="\CadFoot\Model\CadianGogglesHelmet.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camoB",
			"Camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"CadFoot\Data\Textures\GM_Helmet_776_co.paa",
			"CadFoot\Data\Textures\KasrRebreather_776_co.paa",
			"CadFoot\Data\Textures\KasrArmor2_776_co.paa"
		};
		class ItemInfo: HeadgearItem
		{
			mass=45;
			uniformModel="\CadFoot\Model\CadianGogglesHelmet.p3d";
			allowedSlots[]={801,901,701,605};
			modelSides[]={6};
			hiddenSelections[]=
			{
				"camo",
				"camoB",
				"Camo1"
			};
			hiddenSelectionsTextures[]=
			{
				"CadFoot\Data\Textures\GM_Helmet_776_co.paa",
				"CadFoot\Data\Textures\KasrRebreather_776_co.paa",
				"CadFoot\Data\Textures\KasrArmor2_776_co.paa"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=78.75;
					passThrough=0.05;
				};
			};
		};
	};
	
	class LasLMGBase: arifle_MX_Base_F
	{
		author="1st Legion";
		scope=0;
		scopeCurator=0;
		scopeArsenal=0;
		displayName="Unkown Pattern Las-LMG";
		model="\Cadian_Weapons\Model\M36KantRifle.p3d";//Replace with Volker will make.
		reloadAction="GestureReloadMXCompact";
		picture="\Cadian_Weapons\Icon\KantraelLasrifle_ca.paa";
		muzzles[]=
		{
			"this"
		};
		magazineWell[]={};
		magazines[]=
		{
			"150RndLasLmg_mag",
			"200RndLasLmg_mag"
		};
		rightHandIKCurve[]={1};
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\Cadian_Weapons\Anim\M36KantRifle.rtm"
		};
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=80;
			class MuzzleSlot: MuzzleSlot
			{
				linkProxy="\A3\data_f\proxies\weapon_slots\MUZZLE";
				compatibleItems[]={};
				iconPosition[]={0,0.45};
				iconScale=0.2;
			};
			class CowsSlot: CowsSlot
			{
				iconPosition[]={0.5,0.35};
				iconScale=0.2;
				compatibleItems[]=
				{
					"TIOW_2x4xScope_1",
					"TIOW_6xScope_1",
					"TIOW_10xScope_1"
				};
			};
			class PointerSlot: PointerSlot
			{
				iconPosition[]={0.2,0.45};
				iconScale=0.25;
				compatibleItems[]={};
			};
		};
		inertia=0.4;
		aimTransitionSpeed=1.2;
		dexterity=1.6;
		initSpeed=720;
		recoil="recoil_lasgun";
		modelOptics="\DKoK_Weapons\Type14_Optic.p3d";
		class OpticsModes
		{
			class TWS
			{
				opticsID=1;
				useModelOptics=1;
				opticsPPEffects[]=
				{
					"OpticsCHAbera1",
					"OpticsBlur1"
				};
				opticsZoomMin=0.04;
				opticsZoomMax=0.0625;
				opticsZoomInit=0.0625;
				discreteDistance[]={100,200,300,400,500,600,700,800,900,1000,1100,1200,1300,1400,1500,1600};
				discreteDistanceInitIndex=2;
				distanceZoomMin=100;
				distanceZoomMax=1600;
				discretefov[]={0.0625,0.025};
				discreteInitIndex=0;
				modelOptics[]=
				{
					"\A3\Weapons_f\acc\reticle_tws_mg",
					"\A3\Weapons_f\acc\reticle_tws_mg_NFOW"
				};
				memoryPointCamera="opticView";
				visionMode[]=
				{
					"Normal"
				};
				opticsFlare=1;
				opticsDisablePeripherialVision=1;
				cameraDir="";
			};
			class Iron: TWS
			{
				opticsID=2;
				useModelOptics=0;
				opticsPPEffects[]=
				{
					"",
					""
				};
				opticsFlare=0;
				opticsDisablePeripherialVision=0;
				opticsZoomMin=0.15;
				opticsZoomMax=0.4;
				opticsZoomInit=0.5;
				memoryPointCamera="eye";
				visionMode[]={};
				discretefov[]={};
				distanceZoomMin=200;
				distanceZoomMax=200;
				discreteDistance[]={200};
				discreteDistanceInitIndex=0;
			};
		};
		maxZeroing=1000;
		class ItemInfo
		{
			priority=1;
		};
		descriptionShort="Lucius Pattern No.98 Lasgun - Fires at a higher charge range than most lasguns, giving significantly more punch, at the cost of recharge rate and quicker power pack depletion - Power pack only good for 25 shots. Standard issue Death Korps weapon.";
		selectionFireAnim="muzzleFlash";
		modes[]=
		{
			"Single",
			/*"FullAuto",*/
			"Burst",
			"FullAutoSuppression",
			"single_medium_optics1",
			"single_far_optics2"
		};
		class Single: Mode_SemiAuto
		{
			reloadTime=0.096;
			recoil="recoil_pistol_light";
			recoilProne="recoil_prone_pistol_light";
			dispersion=0.00035;
			minRange=200;
			minRangeProbab=0.5;
			midRange=400;
			midRangeProbab=0.7;
			maxRange=750;
			maxRangeProbab=0.3;
			soundContinuous=0;
			soundBurst=0;
			sounds[]=
			{
				"StandardSound"
			};
			class BaseSoundModeType
			{
				closure1[]=
				{
					"\DKoK_Weapons\Sound\close_1.ogg",
					0.316228,
					1,
					10
				};
				closure2[]=
				{
					"\DKoK_Weapons\Sound\close_2.ogg",
					0.316228,
					1.1,
					10
				};
				soundClosure[]={};
			};
			class StandardSound: BaseSoundModeType
			{
				soundSetShot[]=
				{
					"Lasgun_Shot_SoundSet",
					"Lasgun_Tail_SoundSet",
					"Lasgun_InteriorTail_SoundSet"
				};
				begin1[]=
				{
					"\DKoK_Weapons\Sound\close_1.ogg",
					3.1622801,
					1,
					1800
				};
				begin2[]=
				{
					"\DKoK_Weapons\Sound\close_2.ogg",
					3.1622801,
					1,
					1800
				};
				begin3[]=
				{
					"\DKoK_Weapons\Sound\close_3.ogg",
					3.1622801,
					1,
					1800
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin1",
					0.34
				};
				class SoundTails
				{
					class TailInterior
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							2.2387199,
							1,
							1800
						};
						frequency=1;
						volume="interior";
					};
					class TailTrees
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailMeadows
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
		};

		/*
		class FullAuto: Mode_FullAuto
		{
			sounds[]=
			{
				"StandardSound"
			};
			class BaseSoundModeType
			{
				closure1[]=
				{
					"\DKoK_Weapons\Sound\close_1.ogg",
					1,
					1,
					10
				};
				closure2[]=
				{
					"\DKoK_Weapons\Sound\close_1.ogg",
					1,
					1.1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\DKoK_Weapons\Sound\close_1.ogg",
					2.8183801,
					1,
					1200
				};
				begin2[]=
				{
					"\DKoK_Weapons\Sound\close_1.ogg",
					2.8183801,
					1,
					1200
				};
				begin3[]=
				{
					"\DKoK_Weapons\Sound\close_1.ogg",
					2.8183801,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
				class SoundTails
				{
					class TailInterior
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							1.58489,
							1,
							1200
						};
						frequency=1;
						volume="interior";
					};
					class TailTrees
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							1,
							1,
							1200
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							1,
							1,
							1200
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailMeadows
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							1,
							1,
							1200
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							1,
							1,
							1200
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
				SoundSetShot[]=
				{
					"Lasgun_Shot_SoundSet",
					"Lasgun_Tail_SoundSet",
					"Lasgun_InteriorTail_SoundSet"
				};
			};
			soundBurst=0;
			burst=0;
			reloadTime=0.075;
			dispersion=0.00035;
			recoil="recoil_pistol_light";
			recoilProne="recoil_prone_pistol_light";
			minRange=2;
			minRangeProbab=0.3;
			midRange=50;
			midRangeProbab=0.7;
			maxRange=200;
			maxRangeProbab=0.05;
			aiRateOfFire=1;
			aiRateOfFireDistance=250;
		};
		*/

		class FullAutoSuppression: Mode_FullAuto
		{
			sounds[]=
			{
				"StandardSound"
			};
			class BaseSoundModeType
			{
				closure1[]=
				{
					"\DKoK_Weapons\Sound\close_1.ogg",
					1,
					1,
					10
				};
				closure2[]=
				{
					"\DKoK_Weapons\Sound\close_1.ogg",
					1,
					1.1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\DKoK_Weapons\Sound\close_1.ogg",
					2.8183801,
					1,
					1200
				};
				begin2[]=
				{
					"\DKoK_Weapons\Sound\close_1.ogg",
					2.8183801,
					1,
					1200
				};
				begin3[]=
				{
					"\DKoK_Weapons\Sound\close_1.ogg",
					2.8183801,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
				class SoundTails
				{
					class TailInterior
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							1.58489,
							1,
							1200
						};
						frequency=1;
						volume="interior";
					};
					class TailTrees
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							1,
							1,
							1200
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							1,
							1,
							1200
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailMeadows
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							1,
							1,
							1200
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							1,
							1,
							1200
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
				SoundSetShot[]=
				{
					"Lasgun_Shot_SoundSet",
					"Lasgun_Tail_SoundSet",
					"Lasgun_InteriorTail_SoundSet"
				};
			};
			//textureType = "fastAuto"; Never delete this. It was a pain to find.
			soundBurst=0;
			burst=0;
			reloadTime=0.075;
			dispersion=0.008;
			recoil="recoil_pistol_light";
			recoilProne="recoil_prone_pistol_light";
			minRange=2;
			minRangeProbab=0.3;
			midRange=50;
			midRangeProbab=0.7;
			maxRange=200;
			maxRangeProbab=0.05;
			aiRateOfFire=1;
			aiRateOfFireDistance=250;
		};	
		
		class Burst: Mode_Burst
		{
			sounds[]=
			{
				"StandardSound"
			};
			class BaseSoundModeType
			{
				closure1[]=
				{
					"\DKoK_Weapons\Sound\close_1.ogg",
					1,
					1,
					10
				};
				closure2[]=
				{
					"\DKoK_Weapons\Sound\close_1.ogg",
					1,
					1.1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\DKoK_Weapons\Sound\close_1.ogg",
					2.8183801,
					1,
					1200
				};
				begin2[]=
				{
					"\DKoK_Weapons\Sound\close_1.ogg",
					2.8183801,
					1,
					1200
				};
				begin3[]=
				{
					"\DKoK_Weapons\Sound\close_1.ogg",
					2.8183801,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
				class SoundTails
				{
					class TailInterior
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							1.58489,
							1,
							1200
						};
						frequency=1;
						volume="interior";
					};
					class TailTrees
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							1,
							1,
							1200
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							1,
							1,
							1200
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailMeadows
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							1,
							1,
							1200
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"\DKoK_Weapons\Sound\close_1.ogg",
							1,
							1,
							1200
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
				SoundSetShot[]=
				{
					"Lasgun_Shot_SoundSet",
					"Lasgun_Tail_SoundSet",
					"Lasgun_InteriorTail_SoundSet"
				};
			};
			soundBurst=0;
			burst=6;
			reloadTime=0.075;
			dispersion=0.00035;
			recoil="recoil_pistol_light";
			recoilProne="recoil_prone_pistol_light";
			minRange=2;
			minRangeProbab=0.3;
			midRange=50;
			midRangeProbab=0.7;
			maxRange=200;
			maxRangeProbab=0.05;
			aiRateOfFire=1;
			aiRateOfFireDistance=250;
		};

		class single_medium_optics1: Single
		{
			requiredOpticType=1;
			showToPlayer=0;
			minRange=2;
			minRangeProbab=0.2;
			midRange=450;
			midRangeProbab=0.7;
			maxRange=600;
			maxRangeProbab=0.2;
			aiRateOfFire=2;
			aiRateOfFireDistance=600;
		};
		class single_far_optics2: single_medium_optics1
		{
			requiredOpticType=2;
			showToPlayer=0;
			minRange=100;
			minRangeProbab=0.1;
			midRange=500;
			midRangeProbab=0.6;
			maxRange=1200;
			maxRangeProbab=0.05;
			aiRateOfFire=4;
			aiRateOfFireDistance=1200;
		};
		aiDispersionCoefY=6;
		aiDispersionCoefX=4;
	};

	class VanguardLasLMG: LasLMGBase
	{
		author="Dolf";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="[Vanguard] Unkown Pattern Las-LMG";
		hiddenSelections[]=
		{
			"casing_camo",
			"wording_camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Cadian_Weapons\Data\Textures\M36KantRifle_casing_776_co.paa",
			"Cadian_Weapons\Data\Textures\M36KantRifle_wording_co.paa"
		};
		model="\Cadian_Weapons\Model\M36KantRifle.p3d";
	};

	class launch_RPG7_F: Launcher_Base_F
	{
	};

	class MissileLauncherDKOK: launch_RPG7_F
	{
		author="1st legion";
		model="DKoK_Weapons\Model\MissileLauncher.p3d";
		scope=0;
		displayName="Death Korps Missile Launcher";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\DKoK_Weapons\Anim\MissileLauncher.rtm"
		};
		descriptionShort="Death Korps Missile Launcher";
		lockingTargetSound[]=
		{
			"A3\Sounds_F\arsenal\weapons\Launchers\NLAW\locking_NLAW",
			0.316228,
			1
		};
		lockedTargetSound[]=
		{
			"A3\Sounds_F\arsenal\weapons\Launchers\NLAW\locked_NLAW",
			0.316228,
			2.5
		};
		changeFiremodeSound[]=
		{
			"A3\sounds_f\dummysound",
			0.56234097,
			1,
			20
		};
		modelOptics="\A3\Weapons_F\acc\reticle_NLAW";
		opticsPPEffects[]=
		{
			"OpticsCHAbera1",
			"OpticsBlur1"
		};
		opticsZoomMin=0.0623;
		opticsZoomMax=0.0623;
		opticsZoomInit=0.0623;
		class OpticsModes
		{
			class optic
			{
				opticsID=1;
				useModelOptics=1;
				opticsZoomMin=0.0623;
				opticsZoomMax=0.0623;
				opticsZoomInit=0.0623;
				distanceZoomMin=300;
				distanceZoomMax=300;
				memoryPointCamera="cam";
				opticsFlare=1;
				opticsDisablePeripherialVision=1;
				cameraDir="look";
				visionMode[]=
				{
					"Normal",
					"NVG",
					"TI"
				};
				thermalMode[]=
				{
					4,
					5
				};
				opticsPPEffects[]=
				{
					"OpticsCHAbera1",
					"OpticsBlur1"
				};
			};
			class Hamr2Collimator
			{
				opticsID=1;
				useModelOptics=0;
				opticsPPEffects[]=
				{
					"Default"
				};
				opticsFlare=0;
				opticsDisablePeripherialVision=0;
				opticsZoomMin=0.25;
				opticsZoomMax=1.25;
				opticsZoomInit=0.75;
				memoryPointCamera="eye";
				visionMode[]={};
				distanceZoomMin=200;
				distanceZoomMax=200;
			};
		};
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=100;
		};
		magazines[]=
		{
			"MLAT_Mag",
			"MLHE_Mag",
			"MLSmoke_Mag"
		};
		canLock=2;
		weaponLockDelay=5;
		lockAcquire=0;
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\DKoK_Weapons\Data\Textures\MissileLauncherBlack_co.paa"
		};
	};
};
